# Compare web search vs chat

In [1]:
import pandas as pd

In [2]:
web_search = pd.read_excel('../ms-marco-geospatial/interim/cluster_review.xlsx')
web_search

,label,n_samples,representative_query,top_terms,sample_queries,name,group
0,-1,65823,what is the url for the state bank of the lakes,"['county', 'did', 'located', 'does', 'city', '...","['what is at sofala', 'how many killed in sout...",Noise,NaN
1,0,696,area code numbers united states,"['area code', 'code', 'area', 'code area', 'zi...","['long barn california 209- 967 area code', 'w...",Area codes,Administrative
2,1,1054,what's the zip code,"['zip', 'zip code', 'code', 'code zip', 'zip c...","['what is burlington,ky zip code', 'what is th...",ZIP codes,Administrative
3,2,13966,what's the temperature outdoors,"['weather', 'temperature', 'average', 'average...","['what is the weather in nashville tomorrow', ...",Weather & temperature,Temporal
4,3,27761,what is the current minimum wage for ny,"['cost', 'salary', 'average', 'tax', 'average ...","['average annual income in us', 'iphone x pric...","Costs, prices & taxes",Statistical
...,...,...,...,...,...,...,...
101,100,213,what county is jersey city nj,"['nj county', 'nj', 'county', 'jersey county',...","['in what county is wantage township nj', 'wha...",US places,Administrative
102,101,750,what county is farmville nc in,"['county', 'nc', 'nc county', 'sc county', 'sc...","['what county is garland nc in', 'where is bat...",US places,Administrative
103,102,342,what county nashville tn in,"['county', 'tn', 'tn county', 'ky county', 'ky...","['what county is mayfield ky', 'what county is...",US places,Administrative
104,103,869,valencia is in what county in ca,"['county', 'ca county', 'ca', 'california', 'c...","['what county is shafter ca in?', 'where is pa...",US places,Administrative
105,104,381,what county portland in,"['county', 'wa county', 'wa', 'oregon county',...","['what county is franktown colorado in', 'what...",US places,Administrative

In [3]:
chat = pd.read_excel('./interim/cluster_review.xlsx').assign(
    name=lambda df_: df_.name.str.replace('*', ''),
    group=lambda df_: df_.group.str.replace('*', '')
)
chat

,label,n_samples,representative_query,top_terms,sample_queries,name,group,note,sample_query
0,48,76,i need the home address for name_1,"['address', 'address name_1', 'extract', 'zip'...","['describe celestial address.', 'please show m...",Addresses and ZIP codes,Administrative,NaN,please show me different formats of street add...
1,19,66,paris,"['paris', 'paris paris', 'capital paris', 'par...","['what do you think of paris?', 'is paris or l...",Capital cities,Administrative,Paris specifically,tell me about paris.
2,51,62,what is the capital of south africa,"['capital', 'tanzania', 'shortly capital', 'ca...","[""what is the capital of the country that is l...",Capital cities,Administrative,NaN,what is zanzibar know for?
3,59,177,what is the capital of,"['capital', 'capitol', 'spain capital', 'capit...","['what is the capital of england', 'what is th...",Capital cities,Administrative,NaN,what's the capital of texas
4,61,85,whats the capital of france,"['france', 'capital france', 'capital', 'franc...",['what is the capital of france and where is i...,Capital cities,Administrative,Paris specifically,capital of france
...,...,...,...,...,...,...,...,...,...
104,5,107,(in a futuristic city...)\n\nnatsuki: (somehow...,"['natsuki', 'naruto', 'uptown springdale', 'up...","['(in the town of axel...)\n\nsayori: ""what in...",Noise,NaN,anime roleplay scenes?,NaN
105,60,384,quelle est la capitale name_1 france,"['en', 'la', 'name_1', 'di', 'nederlands', 'qu...","[""cos'è il marketing in breve e le 4 p in fran...",Noise,NaN,non-english queries,NaN
106,67,53,can you please help me summarise this webpage?...,"['https', 'https www', 'www', 'com', 'summariz...","['tell me about spires online tutors please, i...",Noise,NaN,summarise a URL,NaN
107,68,169,where can i download open source movies,"['download', 'watch', 'movies', 'vicuna', 'sit...","['hello, can you recommend me 5 sci-fi movies ...",Noise,NaN,where to get free streaming/pirated resource,NaN
108,85,1114,tell me the history of the region of <redacted...,"['redacted', 'redacted redacted', 'did redacte...",['how many grass roots <redacted> organization...,Noise,NaN,cluster based on 'redacted' keyword,NaN

In [4]:
chat.set_index('name')['representative_query'].to_dict()

{'Addresses and ZIP codes': 'i need the home address for name_1',
 'Capital cities': 'whats the capital of france',
 'US states and places': 'please list the states of the us',
 'Birthplaces & residences': 'name_1 is located in the country of',
 'Food permits': 'i want to open a limited sales in florida. how much is a food permit fees?',
 'Professional licensing': 'how much is the initial license fee of board of acupuncture in florida?',
 'Money & business advice': 'i live in serbia. show me how can i quickly earn money online, without any investment.',
 'Stock markets': "give me a report about middle east's fmcg market",
 'Suppliers & B2B sourcing': 'from where i can buy cheap brand shoes for my shop',
 'US state laws (business focus)': 'can you draft me an outline for bylaws for a  wyoming c corporation that is 100% trust owned by a revocable living trust',
 'Australia': 'contents for australia',
 'Canada': 'what is the capital of canada',
 'China & Taiwan': 'tell me something about china',
 'Germany': 'what is the capital of germany',
 'India': 'discription about india',
 'Indonesia': 'can you speak bahasa indonesia',
 'Iran & Egypt': 'tell me about iran',
 'Israel & Palestine': 'tell me a history of israel and palestine',
 'Japan': 'can you tell me about japan',
 'Korea': 'about seoul.',
 'Mexico': 'write me some misconceptions about the history of mexico',
 'Network infrastructure by country': "what's the network address 224.0.0.252 for?",
 'Nordics': 'tell me about finland',
 'Pakistan & Bangladesh': 'write an article on pakistan  for 14th august',
 'Philippines & Malaysia': 'give me information about philippines',
 'Poland': 'poland',
 'Singapore & Hong Kong': 'please tell me about singapore',
 'Turkey': 'what is the capital of turkey',
 'Vietnam': 'translate to vietnam: hello',
 'Film/DVD release dates': 'the spongebob squarepants movie usa released date',
 'Recipes and regional cuisine': 'give me the recipe of tokyo sushi',
 'Football results and predictions': 'can you guess who will become champion of italy, in seria a in soccer',
 'Russia-Ukraine war': 'tell me about the 2022 russian invasion of ukraine',
 'World events': 'give me a point of political situation in the world on 2023',
 'European history': 'thanks for the reply, was there any evidence of a greek colony in acruvium (kotor) before roman era?',
 'Historical battles & wars': 'can you write a summary of the battle of ticonderoga',
 'Presidents': 'who is president of brazil?',
 'Prime ministers': 'who is current prime minister of india',
 'Religion': 'true or false: name_1 had a temple at behbeit el hagar.\\nanswer:',
 'Russia & USSR (history)': 'somthing about russia',
 'Kings and monarchs': 'who is the monarch of the uk',
 'US history': 'summarize the history of the us',
 'US presidents & elections': 'who is the president of usa',
 'Accessing ChatGPT from blocked countries': 'how can i use chatgpt from china?',
 'Beach + social media copy': 'write 10 very short and smart tweets about today saturday sunrise on the beach by the ocean',
 'Censorship by country': 'give me list of websites that are permanetly blocked in russia',
 'GeoGuessr & map projections': 'uploaded an imageyou’re a geo guesser. where is this?',
 'Traffic & urban planning': 'the challenges of the urban areas',
 'US state laws': 'is this legal in their state',
 'Where are you & I from': 'where are you located?',
 'Planets & space': 'what is the distance between the sun and the earth',
 'Flat-earth questions': 'is the earth flat',
 'Mountains & elevation': 'what is the highest mountain',
 'Oceans, water & hydrology': 'the distribution and flow of available water on earth across continents and seasons',
 'Plants, animals & wildlife by region': 'hello, may i please have  some evergreen plants list? that do well in england',
 'Volcanoes, rocks, geology': 'list two features resulting from extrusive volcanic activity in south sudan',
 'Abandoned houses': 'exploring a abandoned house that was built in 1970 but last updated in 2003',
 'Airports': "give me the directions from name_1's airport to its city center",
 'Cars (buying, popularity, licensing)': 'where can i buy a car in israel',
 'Flight booking & airfare': 'i need a flight to london. i am in nyc',
 'Property description & search': 'make a description of 1 bedroom with marina and sea view',
 'Real estate prices & listings': 'write me a offer memo on a retail stnl property in california',
 'Restaurants': 'can you give me good restaurants in juan-les-pins/antibes',
 'Tall buildings & towers': 'whats the tallest building in the world',
 'Country rankings': 'which country has the most people',
 'Crime statistics': 'can you tell me of race and crime statistics in the usa',
 'GDP & national economies': 'give me the gdp per capita for the eu countries',
 'Salaries and taxes by country': 'about w much an it firm pay taxes in based in germany on the information the annual turnover is 25k usd',
 'University rankings': 'tell me something about name_1 university',
 'Time zones': 'what is the time in india',
 'Weather & temperature': 'whats the weather like today',
 'Best places to live / local recommendations': 'write for me a paragraph on the topic the best place to live',
 'Plan a trip to...': 'what are some must see destinations on germany',
 'Top places to visit': 'what are the top 5 places to visit in name_1',
 'Fictional world building': 'create me a made up region with cities, towns, villages, lakes, rivers, mountains for a rpg',
 'Image-generation prompts': 'can you generate an image of beautiful forest',
 'Tell me a joke': "give me a paragraph on funny in farsi's language barrier",
 'Tell me about a place': 'tell me three facts about the city of dinslaken in germany',
 'What if / hypothetical history scenarios': 'what if yugoslavia still exist',
 'Write a (fake) news article': 'write me a satirical “the onion” article about the closure of kiwi farms',
 'Write an application / cover letter': 'give me a email to aks for positions in university for financial aid',
 'Write a blog/social media post': 'write me a blog post about a trip to kinshasa',
 'Write a poem': 'write me a poem about the salish sea where every word starts with m and ends in p',
 'Write a review (hotel/resort)': 'give me 10 prompts about hall way coridor hotel',
 'Write a script (university/college focus)': 'script about u of l vs lsu',
 'Write a short story': 'write a story about name_1\'s visit to the "land of fellatio"',
 'Write a song': 'write me a song about marrickville',
 'Write an analysis': 'statement of problem-introduction chapter 1 dissertation harnessing blockhain to eradicate poverty in africa',
 'Write an essay': 'essay on the now continent zealandia in 100-200 words with title',
 'Noise': 'tell me the history of the region of <redacted> currently known as <redacted> please.'}

In [7]:
chat[chat.label == 19].sample_queries.iloc[0]

"['what do you think of paris?', 'is paris or london prettier?', 'info on paris', 'tell me about paris.', 'stravinsky collaborated with what ballet company during his years in paris?', 'the capital of paris is', 'where is paris', 'what did paris look like during 9000 bc (plus population)?', 'how fra is paris from netherthong', 'describe paris']"